#' Run The gre Sampler
#'
#' This function samples the correlation adjustment described in (cite).
#' State is stored internally; nothing is returned.
#'
#' @param ptr An external pointer generated by the initialize_gre() function.
#'
#' @return Nothing.
#' @export
#' @examples
#' run(greObj)
run <- function(ptr) {
  invisible(.Call(.run, ptr))
}
